# Generated by Django 3.0.6 on 2020-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20200503_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='displayImage',
            field=models.ImageField(default='defaultProject.png', upload_to=''),
        ),
    ]
