# Generated by Django 3.0.5 on 2020-05-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20200508_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='carouselimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselimage', models.ImageField(default='defaultProject.png', upload_to='images/carousel')),
                ('carouseltitle', models.CharField(max_length=100)),
                ('carouseldesc', models.TextField()),
            ],
        ),
    ]
