# Generated by Django 3.0.5 on 2020-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_merge_20200508_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='photo',
            field=models.ImageField(default='defaultProject.png', upload_to='images'),
        ),
    ]
