# Generated by Django 3.0.5 on 2020-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_faculties_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(default='defaultProject.png', upload_to='images'),
        ),
    ]
