# Generated by Django 3.0.5 on 2020-05-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='jointCore',
            new_name='insta_id',
        ),
        migrations.AddField(
            model_name='club',
            name='core_email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='jointcore',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='core',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
