# Generated by Django 3.0.5 on 2020-05-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Clubs', '0004_club_displayimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='upcoming_events',
            field=models.ManyToManyField(blank=True, related_name='Club', to='Home.Events'),
        ),
    ]
