# Generated by Django 3.0.5 on 2020-05-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20200502_0431'),
        ('Projects', '0003_auto_20200502_1021'),
    ]

    operations = [
    ]
