# Generated by Django 3.0.5 on 2020-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_project_displayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='displayImage',
            field=models.ImageField(default='defaultProject.jpeg', upload_to=''),
        ),
    ]
