# Generated by Django 3.0.5 on 2020-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20200505_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='displayImage',
            field=models.ImageField(default='defaultProject.png', upload_to='images'),
        ),
    ]
