# Generated by Django 3.0.6 on 2020-05-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20200506_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='company',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
