# Generated by Django 3.0.5 on 2020-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20200506_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='profilePic',
            field=models.ImageField(default='defaultProfile.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='students',
            name='profilePic',
            field=models.ImageField(default='defaultProfile.png', upload_to='images'),
        ),
    ]
