# Generated by Django 3.0.5 on 2020-05-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20200508_1042'),
        ('Projects', '0009_auto_20200508_1953'),
    ]

    operations = [
    ]
