# Generated by Django 3.0.6 on 2020-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=500)),
                ('admin_name', models.CharField(max_length=20)),
                ('query', models.ManyToManyField(blank=True, related_name='replies', to='Forum.query')),
            ],
        ),
        migrations.DeleteModel(
            name='queries',
        ),
    ]
