# Generated by Django 3.0.6 on 2020-05-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20200509_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
